version: '3.8'

services:
  docugenius-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: docugenius-backend
    ports:
      - "3000:3000"  # Node.js API
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=debug  # Set log level to debug for more verbose logging
      # Use environment variables for API keys
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=nvidia/llama-3.1-nemotron-nano-8b-v1:free
      - ENABLE_ZERO_PERSISTENCE=${ENABLE_ZERO_PERSISTENCE}
      - MAX_REPO_SIZE_MB=${MAX_REPO_SIZE_MB}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./logs:/app/logs
      - ./temp:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s 